### ISSUE TITLE
Calorie Budget Display

### ISSUE THREAD

**Issue by iltep64** [AY1920S1-CS2103T-W11-4/main#11]
- [x] Add a progress bar representing today's calorie budget
    - [x] Basic display of current/total calories
    - [ ] (Optional) UI animations
- [x] Add `set` command to adjust calorie budget
