### ISSUE TITLE
Display Calorie intake Statistics

### ISSUE THREAD

**Issue by FelixNWJ** [AY1920S1-CS2103T-W11-4/main#17]
- [x] Report display is generated
    - [x] Maximum calorie intake per day of current month displayed
    - [x] Average calorie intake per day of current month displayed
    - [x] Minimum calorie intake per day of current month displayed
