### ISSUE TITLE
Meal suggestion for the user

### ISSUE THREAD

**Issue by MauriceTXS** [AY1920S1-CS2103T-W11-4/main#18]
- [x] Suggest meals for user
    - [x] Get remaining amount of calories and check it against data base
    - [x] Calculate and suggest meals accordingly

**Comment by FelixNWJ** [comment]
Close #53
