### ISSUE TITLE
Display Exceeded Calorie Budget and Most Consumed Food

### ISSUE THREAD

**Issue by FelixNWJ** [AY1920S1-CS2103T-W11-4/main#19]
- [x] Number of days where calorie exceeded displayed

- [x] Most consumed food of the month displayed

- [x] Format of Report is adjusted for user readability
