### ISSUE TITLE
Notify missed meal to users

### ISSUE THREAD

**Issue by MauriceTXS** [AY1920S1-CS2103T-W11-4/main#20]
- [x] Notify user
    - [x] Check meal timing
    - [x] Compare with usual eating time database
    - [x] Notify user if timing missed
