### ISSUE TITLE
Add Command

### ISSUE THREAD

**Issue by fangpinsern** [AY1920S1-CS2103T-W11-4/main#21]
- [x] Add to the file
    - [x] Change how the food object is saved in file from AB3
- [x] Change the fields to Calories, Location etc

**Comment by FelixNWJ** [comment]
Close and solved by #52
