### ISSUE TITLE
Edit and delete feature

### ISSUE THREAD

**Issue by fangpinsern** [AY1920S1-CS2103T-W11-4/main#72]
- [x] Delete meal from meal log
- [x] Edit
  - [x] Edit only the Name
  - [x] Edit only the Calorie
  - [x] Edit only the tags
  - [x] Combined Edit
  - [x] Add edited dish into DishDB
